-- VIEWS --
SELECT *
FROM V_BOOK_GENRE_COMEDY;

SELECT *
FROM V_BOOK_GENRE_DRAMA;

SELECT *
FROM V_BOOK_GENRE_FANTASY;

SELECT *
FROM V_BOOK_GENRE_THRILLER;

SELECT *
FROM V_ALL_PROD_SKU_CATEGORY;

SELECT *
FROM V_ORDER_PRODUCTS_INFO;

-- FUNCTIONS --

SELECT *
FROM TABLE(FN45419.GET_PROD_INFO(100119));

SELECT FN45419.ORD_STAT_INFO(ORDERNO)
FROM ORDER;

SELECT DISTINCT FN45419.ORD_STAT_INFO('22')
FROM ORDER;

SELECT FN45419.IS_EMAIL_OCP(EMAIL)
FROM MEMBER;

SELECT DISTINCT FN45419.IS_EMAIL_OCP('dummymail@gmail.com')
FROM MEMBER;

SELECT CITY, NEIGHBOURHOOD, POSTALCODE, FN45419.NUM_OF_PEOPLE(ID)
FROM ADDRESS;

SELECT SUM(FN45419.NUM_OF_PEOPLE(ID)) AS ALL_PEOPLE
FROM ADDRESS;