-- BOOK --
ALTER TABLE BOOK
    ADD CONSTRAINT PK_BOOK PRIMARY KEY (SKU);

ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_VENDORID FOREIGN KEY (VENDORID)
        REFERENCES VENDOR (ID);

ALTER TABLE BOOK
    ADD CONSTRAINT CH_BARCODE CHECK (LENGTH(BARCODE) = 12);

ALTER TABLE BOOK
    ADD CONSTRAINT CH_CATEGORY CHECK (CATEGORY IN ('book'));

-- NOTEBOOK --
ALTER TABLE NOTEBOOK
    ADD CONSTRAINT PK_NOTEBOOK PRIMARY KEY (SKU);

ALTER TABLE NOTEBOOK
    ADD CONSTRAINT FK_NOTEBOOK_VENDOR_ID FOREIGN KEY (VENDORID)
        REFERENCES VENDOR (ID);

ALTER TABLE NOTEBOOK
    ADD CONSTRAINT CH_BARCODE CHECK (LENGTH(BARCODE) = 12);

ALTER TABLE NOTEBOOK
    ADD CONSTRAINT CH_CATEGORY CHECK (CATEGORY IN ('notebook'));

ALTER TABLE NOTEBOOK
    ADD CONSTRAINT CH_FORMAT CHECK (FORMAT IN ('A2', 'A3', 'A4', 'A5', 'A6'));

ALTER TABLE NOTEBOOK
    ADD CONSTRAINT CH_RECYCLPAPER CHECK (RECYCLPAPER IN ('y', 'n'));

-- PEN --
ALTER TABLE PEN
    ADD CONSTRAINT PK_PEN PRIMARY KEY (SKU);

ALTER TABLE PEN
    ADD CONSTRAINT FK_PEN_VENDOR_ID FOREIGN KEY (VENDORID)
        REFERENCES VENDOR (ID);

ALTER TABLE PEN
    ADD CONSTRAINT CH_BARCODE CHECK (LENGTH(BARCODE) = 12);

ALTER TABLE PEN
    ADD CONSTRAINT CH_CATEGORY CHECK (CATEGORY IN ('pen'));

-- PENCIL --
ALTER TABLE PENCIL
    ADD CONSTRAINT PK_PENCIL PRIMARY KEY (SKU); 

ALTER TABLE PENCIL
    ADD CONSTRAINT FK_PENCIL_VENDOR_ID FOREIGN KEY (VENDORID)
        REFERENCES VENDOR (ID);

ALTER TABLE PENCIL
    ADD CONSTRAINT CH_BARCODE CHECK (LENGTH(BARCODE) = 12);

ALTER TABLE PENCIL
    ADD CONSTRAINT CH_CATEGORY CHECK (CATEGORY IN ('pencil'));

ALTER TABLE PENCIL
    ADD CONSTRAINT CH_ERASER CHECK (ERASER IN ('y', 'n'));

-- ALLSKU --
ALTER TABLE ALLSKU
    ADD CONSTRAINT PK_ALLSKU PRIMARY KEY (SKU);

-- ORDER --
ALTER TABLE ORDER
    ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDERNO);

ALTER TABLE ORDER
    ADD CONSTRAINT FK_ORDER_PAYMENT FOREIGN KEY (CARDNO)
        REFERENCES PAYMENT (CARDNO);

-- MEMBER --
ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (EMAIL);

ALTER TABLE MEMBER
    ADD CONSTRAINT FK_MEMBER_ADDRESS FOREIGN KEY (IDADDRESS)
        REFERENCES ADDRESS (ID);

ALTER TABLE MEMBER
    ADD CONSTRAINT CH_EMAIL CHECK (EMAIL LIKE '%_@%_.%_');

-- PAYMENT --
ALTER TABLE PAYMENT
    ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (CARDNO);

-- ADDRESS --
ALTER TABLE ADDRESS
    ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ID);

ALTER TABLE ADDRESS
    ADD CONSTRAINT CH_ID CHECK (ID > 0);

ALTER TABLE ADDRESS
    ADD CONSTRAINT CH_APARTAMENTNO CHECK (APARTMENTNO > 0);

ALTER TABLE ADDRESS
    ADD CONSTRAINT CH_POSTALCODE CHECK (POSTALCODE > 0);

-- BASKET --
ALTER TABLE BASKET
    ADD CONSTRAINT PK_BASKET PRIMARY KEY (ID);

ALTER TABLE BASKET
    ADD CONSTRAINT FK_BASKET_ORDER FOREIGN KEY (ORDERNO)
        REFERENCES ORDER (ORDERNO);

ALTER TABLE BASKET
    ADD CONSTRAINT FK_BASKET_PAYMENT FOREIGN KEY (CARDNO)
        REFERENCES PAYMENT (CARDNO);

ALTER TABLE BASKET
    ADD CONSTRAINT FK_BASKET_PRODUCT FOREIGN KEY (SKU)
        REFERENCES ALLSKU (SKU);

ALTER TABLE BASKET
    ADD CONSTRAINT FK_BASKET_MEMBER FOREIGN KEY (EMAIL)
    REFERENCES MEMBER(EMAIL);  

ALTER TABLE BASKET
    ADD CONSTRAINT CH_TOTALPRICE CHECK (TOTALPRICE > 0);     

-- VENDOR --
ALTER TABLE VENDOR
    ADD CONSTRAINT PK_VENDOR PRIMARY KEY (ID);

ALTER TABLE VENDOR
    ADD CONSTRAINT CH_EMAIL CHECK (EMAIL LIKE '%_@%_.%_');

-- VENDORADDRESS
ALTER TABLE VENDORADDRESS
    ADD CONSTRAINT PK_VENDORADDRESS PRIMARY KEY (ID);

ALTER TABLE VENDORADDRESS
    ADD CONSTRAINT FK_VENDORADDRESS_VENDOR FOREIGN KEY (IDVENDOR)
        REFERENCES VENDOR (ID);

ALTER TABLE VENDORADDRESS
    ADD CONSTRAINT FK_VENDORADDRESS_ADDRESS FOREIGN KEY (IDADDRESS)
        REFERENCES ADDRESS (ID);