-- VIEWS --
SELECT *
FROM V_BOOK_GENRE_COMEDY;

SELECT *
FROM V_BOOK_GENRE_DRAMA;

SELECT *
FROM V_BOOK_GENRE_FANTASY;

SELECT *
FROM V_BOOK_GENRE_THRILLER;

SELECT *
FROM V_ALL_PROD_SKU_CATEGORY;

SELECT T.*
FROM V_ORDER_PRODUCTS_INFO AS T
ORDER BY T.ORDERNO;

SELECT * 
FROM FN45419.V_MEMBER_INFO;

-- FUNCTIONS --

SELECT *
FROM TABLE(FN45419.GET_PROD_INFO(100119));

SELECT FN45419.ORD_STAT_INFO(ORDERNO)
FROM ORDER;

SELECT DISTINCT FN45419.ORD_STAT_INFO('22')
FROM ORDER;

SELECT FN45419.IS_EMAIL_OCP(EMAIL)
FROM MEMBER;

SELECT DISTINCT FN45419.IS_EMAIL_OCP('dummymail@gmail.com')
FROM MEMBER;

SELECT CITY, NEIGHBOURHOOD, POSTALCODE, FN45419.NUM_OF_PEOPLE(ID)
FROM ADDRESS;

SELECT SUM(FN45419.NUM_OF_PEOPLE(ID)) AS ALL_PEOPLE
FROM ADDRESS;

SELECT DISTINCT T.SKU, T.CATEGORY, T.PRICE
FROM BOOK AS B,
     TABLE(FN45419.MOST_EXP_PROD(B.CATEGORY)) AS T;

SELECT DISTINCT T.SKU, T.CATEGORY, T.PRICE
FROM BOOK AS B,
     TABLE(FN45419.MOST_UNEXP_PROD(B.CATEGORY)) AS T;

SELECT T.ORDERNO, T.STATUS, T.TOTAL
FROM  MEMBER AS M,
     TABLE(FN45419.MEMB_ORDER_HIST(M.EMAIL)) AS T;

VALUES(FN45419.AMT_MONEY_SPENT('camélia.pevreal@hud.gov'));

VALUES(FN45419.COUNT_ORD_BY_MEMBER('camélia.pevreal@hud.gov'));

VALUES(FN45419.IS_EXPIRED(3538)); --NON-EXPIRED

VALUES(FN45419.IS_EXPIRED(356)); --EXPIRED
