CREATE VIEW V_BOOK_GENRE_COMEDY
AS
SELECT *
FROM BOOK
WHERE GENRE = 'comedy';

CREATE VIEW V_BOOK_GENRE_DRAMA
AS
SELECT *
FROM BOOK
WHERE GENRE = 'drama';

CREATE VIEW V_BOOK_GENRE_THRILLER
AS
SELECT *
FROM BOOK
WHERE GENRE = 'thriller';

CREATE VIEW V_BOOK_GENRE_FANTASY
AS
SELECT *
FROM BOOK
WHERE GENRE = 'fantasy';

CREATE VIEW V_ORDER_PRODUCTS_INFO
AS
SELECT O.ORDERNO,
       T.BARCODE,
       T.CATEGORY,
       T.SINGLEPRICE,
       B.TOTALPRICE,
       B.QUANTITY
FROM ORDER AS O
         INNER JOIN BASKET B on O.ORDERNO = B.ORDERNO,
     TABLE(FN45419.GET_PROD_INFO(B.SKU)) AS T;

CREATE VIEW V_ALL_PROD_SKU_CATEGORY
AS
SELECT SKU, CATEGORY
FROM BOOK

UNION
SELECT SKU, CATEGORY
FROM NOTEBOOK

UNION
SELECT SKU, CATEGORY
FROM PEN

UNION
SELECT SKU, CATEGORY
FROM PENCIL;